// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: adder.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TelegramBot_GetMessages_FullMethodName = "/proto.TelegramBot/GetMessages"
)

// TelegramBotClient is the client API for TelegramBot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelegramBotClient interface {
	GetMessages(ctx context.Context, in *MessageRequestTelegram, opts ...grpc.CallOption) (*MessageResponse, error)
}

type telegramBotClient struct {
	cc grpc.ClientConnInterface
}

func NewTelegramBotClient(cc grpc.ClientConnInterface) TelegramBotClient {
	return &telegramBotClient{cc}
}

func (c *telegramBotClient) GetMessages(ctx context.Context, in *MessageRequestTelegram, opts ...grpc.CallOption) (*MessageResponse, error) {
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, TelegramBot_GetMessages_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelegramBotServer is the server API for TelegramBot service.
// All implementations must embed UnimplementedTelegramBotServer
// for forward compatibility
type TelegramBotServer interface {
	GetMessages(context.Context, *MessageRequestTelegram) (*MessageResponse, error)
	mustEmbedUnimplementedTelegramBotServer()
}

// UnimplementedTelegramBotServer must be embedded to have forward compatible implementations.
type UnimplementedTelegramBotServer struct {
}

func (UnimplementedTelegramBotServer) GetMessages(context.Context, *MessageRequestTelegram) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessages not implemented")
}
func (UnimplementedTelegramBotServer) mustEmbedUnimplementedTelegramBotServer() {}

// UnsafeTelegramBotServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelegramBotServer will
// result in compilation errors.
type UnsafeTelegramBotServer interface {
	mustEmbedUnimplementedTelegramBotServer()
}

func RegisterTelegramBotServer(s grpc.ServiceRegistrar, srv TelegramBotServer) {
	s.RegisterService(&TelegramBot_ServiceDesc, srv)
}

func _TelegramBot_GetMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequestTelegram)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramBotServer).GetMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramBot_GetMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramBotServer).GetMessages(ctx, req.(*MessageRequestTelegram))
	}
	return interceptor(ctx, in, info, handler)
}

// TelegramBot_ServiceDesc is the grpc.ServiceDesc for TelegramBot service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelegramBot_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TelegramBot",
	HandlerType: (*TelegramBotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMessages",
			Handler:    _TelegramBot_GetMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "adder.proto",
}
